# Change these first
owner: mattomc # Your GitHub organization or username, where this repository lives
repo: ugaupptime # The name of this repository

sites:
  - name: San Andreas First Responders [Community Management Panel]
    url: https://cms.safrgaming.com
  - name: United Gaming Alliance
    url: https://forum.unitedgamingalliance.com
  - name: United Gaming Alliance Virtual Airline
    url: https://va.unitedgamingalliance.com
  - name: Minecraft
    check: "tcp-ping"
    url: 149.28.42.129
    port: 25565 
  - name: 7D2D
    check: "tcp-ping"
    url: 149.28.42.129
    port: 26900 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.unitedgamingalliance.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: United Gaming alliance Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: United Gaming Alliance UPTIME Status Website
  navbar:
    - title: Status
      href: /
    - title: MGMC AU
      href: https://www.mgmc.au

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
